= Go samples - from zero to guru
Jarkko <@jkangasluoma>
v0.2, 2019-06-28
:toc:
:data-uri:

// Note: Convert adoc to HTML with the asciidoctor utility, optionally with the flag -a data-uri to embed linked content.

== What is it?

I've been learning Go a bit. This repo contains sample code to share the joy of learning. Should you find it interesting I encourage also taking a look at the links to other sources I've collected. As these things go, Go is in rapid evolution, and better conventions and practices pop up.

Content is inspired by Todd Mcleod's professional Go training courses and material at https://github.com/GoesToEleven. It's truly tasty stuff.

If you've taken a look at a previous version of this repository, there's now a <<brief-changelog,brief changelog>>.

== Get started now

Go is great. Let's hear it from the authorities: https://youtu.be/IPOvrK3S3gQ?list=PLhr1KZpdzukcZIPswLEcVzw8HKF_yM0r3&t=1230 (excerpt from AWS re:invent 20:30 through 22:30).

Need to install:

- brew install go

Need an IDE:

- https://code.visualstudio.com/docs/languages/go
- https://www.jetbrains.com/go/ (GoLand 30-day trial)

Need docs:

- https://golang.org/ref/spec
- https://golang.org/doc/effective_go.html

Need to hack:

- https://play.golang.org/ (Go and share!)
- https://tour.golang.org/welcome/1 (Go and learn!)

== Go setup more in-depth

Instructions for Mac (see Windows notes in the bottom of the chapter). Download manually or use Brew:

_brew install go_

Source code and dependencies are made available globally relying on a few environment variables that should be set up fine automatically.

Having installed the tooling, go ahead and try out some of the useful _Go_ command line tool commands to familiarize yourself with its output (maybe also check out where artifacts are produced):

- go env
- go help gopath
- go run src/dive-in/001-hello/you-go.go
- go build -o bin/main src/dive-in/001-hello/you-go.go
- go install src/dive-in/001-hello/you-go.go

Note: Before Go modules were introduced I tended to change _GOPATH_ to the project's src folder, my experience being that 99.9% of setup issues are due to conflicting env variables (in order of culpability):

- GOPATH (your workspace, one folder, any name, any location)
- GOROOT (Go installation directory)
- GOBIN (installation directory for buildables)

With regards to IDEs, they may also require GOPATH to be set somewhere in their configs. It's a good idea to check command line tooling first.

On Windows I find https://chocolatey.org/ nice:

_choco install golang_

Set Windows environment variables similarly to above via e.g. Control panel - Advanced. Or giddy up all with Bash on Windows and apt-get goodness.

== Dive-in examples

In addition to the _go_ command examples mentioned previously, you can run the examples using _make_ (on OSX installed as part of Xcode):

_cd src/dive-in/ && make run-001_

=== 001 Go world

This program prints text. Points of note:

_package main_

_import_

_func main_, optionally with arguments.

_fmt_ package, see https://godoc.org/fmt, testing, visibility specifiers. Upper case for global visibility, lower case for package visible.

Control structures: sequential, looping, conditional.

Unit testing.

=== 002

This program shows higher order functions for a tasty little sampler, a few extra keywords and string slice manipulation.

_strings_

Slices, e.g. https://golang.org/ref/spec#Appending_and_copying_slices

=== 003

_net/http_ for the simplest web server possible.

=== 004

https://docs.aws.amazon.com/lambda/latest/dg/lambda-golang.html[AWS Lambda] sample. Main, Lambda handler. Contains build and deploy script templates.

== [[brief-changelog]]Brief changelog

2020-04 Go's dependency management is now called https://blog.golang.org/using-go-modules[Go modules] and is in a very usable state from what I've experienced with VSCode toolchain getting there. Previously Go dependency management relied on a tool called _dep_, which continues to live on as a separate entity. These changes simplify setup greatly.

== FAQ

1. Is Go a functional programming language, ie. does it promote making data immutable and state, if any, transparent?

Let me Google that for you: https://medium.com/@geisonfgfg/functional-go-bc116f4c96a4. Go offers _const_, array slicing, higher order functions, but it's not a firm proponent of functional style, but does instead enforce strict scoping.
