build:
	dep ensure -v
	go build -o bin/hello 001-hello/you-go.go
	go build -o bin/web 002-web/web.go
	go build -o bin/web 003-once-more-unto-the-breach-dear-friends/main.go

run-001:
	go run 001-hello/you-go.go

run-002:
	go run 002-web/web.go

run-003:
	go run 003-once-more-unto-the-breach-dear-friends/main.go
